### ISSUE TITLE
Opening main menu for the second time shows error

### ISSUE THREAD

**Issue by s1dsq** [chimay/wheel#2]
_E95: Buffer with this name already exists_
This issue disappears if I remove `set hidden` from my vimrc.
Can the wheel buffer type have the option `setlocal bufhidden=unload` instead of it being empty?

**Comment by chimay** [comment]
in fact, the plugin save wheel buffers in a stack, in case you want to save search for instance. So, it's best to set it to bufhidden. My guess is that you accidentally push a buffer to the stack and opened the same menu.

To avoid this error, I added the buf number to the pseudo-filename, it should be ok now.

thanks to help me improve.

**Comment by s1dsq** [comment]
The fix worked. Thanks for the awesome plugin!
